// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/swaggo/swag",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/category/list": {
            "get": {
                "description": "获取文章分类列表，包含了该分类下文章的统计数目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "分类列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.CategoryListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/post/detail": {
            "get": {
                "description": "获取文章详情，包括用户和分类信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "文章详情",
                "parameters": [
                    {
                        "enum": [
                            "html"
                        ],
                        "type": "string",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "post_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.PostDetailResp"
                        }
                    }
                }
            }
        },
        "/api/v1/post/list": {
            "get": {
                "description": "获取文章列表，支持分页，可按分类id进行查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "post"
                ],
                "summary": "文章列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/req.GetPostListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.PostListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/user/signin": {
            "post": {
                "description": "检查用户是否存在，密码是否正确，如果正常，返回用户token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登陆",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/req.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "111001": {
                        "description": "参数错误",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.SignInResp"
                        }
                    }
                }
            }
        },
        "/api/v1/user/signout": {
            "post": {
                "description": "用户退出登陆，需要在header中附带x-user-token参数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户退出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/renderx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/signup": {
            "post": {
                "description": "创建新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/req.SignupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/renderx.Response"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "ping,检查服务是否正常",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/renderx.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CategoryBrief": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "\"2006-01-02 15:05:05\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "同上",
                    "type": "string"
                }
            }
        },
        "dto.CategoryList": {
            "type": "object",
            "properties": {
                "cate_id": {
                    "description": "分类id",
                    "type": "integer"
                },
                "cate_name": {
                    "description": "分类名称",
                    "type": "string"
                },
                "post_count": {
                    "description": "该分类下的文章数",
                    "type": "integer"
                }
            }
        },
        "dto.PostBrief": {
            "type": "object",
            "properties": {
                "cate_id": {
                    "type": "integer"
                },
                "created_at": {
                    "description": "\"2006-01-02 15:05:05\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "title_en": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "同上",
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UserBrief": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "\"2006-01-02 15:05:05\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "同上",
                    "type": "string"
                }
            }
        },
        "renderx.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "result": {
                    "$ref": "#/definitions/renderx.Result"
                }
            }
        },
        "renderx.Result": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "req.GetPostListReq": {
            "type": "object",
            "properties": {
                "cate_id": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "req.SignInReq": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "req.SignupReq": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "resp.CategoryListResp": {
            "type": "object",
            "properties": {
                "cate_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CategoryList"
                    }
                },
                "total": {
                    "description": "文章分类的总数目",
                    "type": "integer"
                }
            }
        },
        "resp.PostDetailResp": {
            "type": "object",
            "properties": {
                "cate_id": {
                    "type": "integer"
                },
                "category": {
                    "$ref": "#/definitions/dto.CategoryBrief"
                },
                "content": {
                    "description": "文章详情",
                    "type": "string"
                },
                "created_at": {
                    "description": "\"2006-01-02 15:05:05\"",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "title_en": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "同上",
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserBrief"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "resp.PostListResp": {
            "type": "object",
            "properties": {
                "post_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PostBrief"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "resp.SignInResp": {
            "type": "object",
            "properties": {
                "user_token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8030",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "yonder blog api aservice",
	Description:      "yonder博客的后端API服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
