basePath: /
definitions:
  renderx.Response:
    properties:
      data: {}
      result:
        $ref: '#/definitions/renderx.Result'
    type: object
  renderx.Result:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  req.CreateUserReq:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
host: localhost:8030
info:
  contact: {}
  description: yonder博客的后端API服务
  termsOfService: http://swagger.io/terms/
  title: yonder blog api
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: 新用户注册
      parameters:
      - description: 查询参数
        in: body
        name: object
        schema:
          $ref: '#/definitions/req.CreateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/renderx.Response'
      summary: 创建用户
      tags:
      - users
swagger: "2.0"
