FROM ubuntu:20.04

RUN apt update
RUN apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev \
    libnss3-dev libssl-dev libreadline-dev libffi-dev wget libmysqlclient-dev
RUN apt install -y python3 python3-pip


