version: '3'

networks:
  yonder-net:
    driver: bridge

services:
  # 在服务中连接时，host部分直接用这里的名称mysql即可
  mysql:
    image: mysql:8.3.0
    container_name: yonder-mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - /var/yonder/mysql:/var/lib/mysql
    networks:
      - yonder-net
    healthcheck:
        test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10

  redis:
    image: redis:7.0
    container_name: yonder-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - yonder-net

  server:
    image: yonder-server-py:latest
    container_name: yonder-server-py
    restart: always
    ports:
      - "6070:6070"
    volumes:
      - /var/yonder/logs:/var/yonder/logs
    networks:
      - yonder-net
    depends_on:
      mysql:
        condition: service_healthy
      # redis
      #   condition: service_completed_successfully

  frontend:
    image: yonder-frontend:latest
    container_name: yonder-frontend
    restart: always
    # 对外开放访问的端口
    ports:
      - "6050:6050"
    depends_on:
      - server
    networks:
      - yonder-net

