FROM ubuntu-base

RUN mkdir /frontend_vue 
WORKDIR /frontend_vue

# 先安装依赖包
COPY src/frontend_vue/package*.json ./
RUN npm install

# 复制源码
COPY src/frontend_vue .

EXPOSE 6050

RUN npm run build

CMD [ "npm", "run", "start" ]
